site_name: ReDU Documentation
pages:
    - ReDU Introduction: index.md
    - How to Contribute: HowtoContribute.md
    - Analyze Your Data:
        - Multivariate - Project Your Data: AnalyzeYourData_MultivariateComparisons.md
        - Co-Analysis at GNPS: AnalyzeYourData_CoAnalysis_at_GNPS.md
    - Analyze Public Data:
        - Multivariate - Explore Public Data: AnalyzePublicData_MultivariateComparisons.md
        - Chemical Explorer and Sample Information Association: AnalyzePublicData_ChemicalExplorerSampleInformationAssociation.md
        - Re-analysis at GNPS: PublicData_Reanalysis_at_GNPS.md
    - Contact: contact.md
    - FAQ: FAQ.md
theme:
    name: material
    #name: readthedocs

    #palette:
    #    primary: 'light blue'
    #    accent: 'orange'
    #font:
    #    text: 'Roboto'
    #    code: 'Roboto Mono'

    #logo: 'img/GNPS_logo.jpg'
#theme: readthedocs
#theme:
#  name: 'rtd-dropdown'

mkdocs.yml
docs/
    AnalyzeYourData_MutlivariateComparisons.md
    AnalyzeYourData_CoAnalysis_at_GNPS.md
    AnalyzePublicData_MultivariateComparisons.md
    AnalyzePublicData_ChemicalExplorerSampleInformationAssociation.md
    PublicData_Reanalysis_at_GNPS.md
    contact.md
    index.md
    FAQ.md
    HowtoContribute.md
    images/
        File_Selector.gif
        PCA_Emperor_PublicData.gif
        Projection.gif
        SampleInfoAssociation.gif
        Sample_Template_Fill.gif
        Sample_Template_deleterows.gif
        Validate.gif
        axis_change.gif
        color_change.gif
        filter_samples.gif
        find_task_id.jpg
        redu_homepage.jpg
        redu_home.jpg
        task_id_entry.jpg
        Sample_Template_MakeACopy.gif


google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
